// app/api/register/route.ts
import { NextResponse } from "next/server";
import { z } from "zod";
import { PrismaClient } from "@prisma/client";
import { nanoid } from "nanoid";
import { standardizeAmount } from "@/lib/currency";

import { sendRegistrationConfirmation } from "@/lib/email-service";

const prisma = new PrismaClient();

// Helper to generate system reference
function generateSystemReference(): string {
  const timestamp = Date.now().toString(36).toUpperCase();
  const random = nanoid(6).toUpperCase();
  return `NAOSA-${timestamp}-${random}`;
}

// Validation schema for registration
const registrationSchema = z.object({
  firstName: z.string().min(1, "First name is required"),
  middleName: z.string().optional().nullable(),
  surname: z.string().min(1, "Surname is required"),
  gender: z.enum(["male", "female"]),
  currentAddress: z.string().min(5, "Address is required"),
  city: z.string().min(2, "City is required"),
  country: z.string().min(2, "Country is required").default("Sierra Leone"),
  admissionNumber: z.string().optional().nullable(),
  dateOfEntry: z.string().min(1, "Date of entry is required"),
  dateOfExit: z.string().min(1, "Date of exit is required"),
  email: z.string().email("Invalid email").optional().nullable(),
  phone: z.string().min(6, "Phone number is required"),
  registrationAmount: z.number().min(0, "Amount must be positive"),
  transactionReference: z.string().min(1, "Transaction reference is required"),
});

export async function POST(request: Request) {
  try {
    const body = await request.json();

    // Validate request body
    const validationResult = registrationSchema.safeParse(body);

    if (!validationResult.success) {
      return NextResponse.json(
        {
          error: "Validation failed",
          details: validationResult.error.issues,
        },
        { status: 400 },
      );
    }

    const data = validationResult.data;

    // Standardize the amount (convert Old Leone to New Leone if needed)
    const standardizedAmount = standardizeAmount(data.registrationAmount);

    const systemReference = generateSystemReference();
    const memberName =
      `${data.firstName} ${data.middleName || ""} ${data.surname}`
        .trim()
        .replace(/\s+/g, " ");

    // Check if member already exists
    const existingMember = await prisma.member.findFirst({
      where: {
        OR: [
          { email: data.email || undefined },
          { phone: data.phone },
          { transactionReference: data.transactionReference },
        ],
      },
    });

    if (existingMember) {
      return NextResponse.json(
        {
          error:
            "Member with this email, phone, or transaction reference already exists",
        },
        { status: 409 },
      );
    }

    // Check if admission number already exists (using findFirst since findUnique expects unique field)
    if (data.admissionNumber) {
      const existingAdmissionNumber = await prisma.member.findFirst({
        where: {
          admissionNumber: data.admissionNumber,
        },
      });

      if (existingAdmissionNumber) {
        return NextResponse.json(
          { error: "Admission number already registered" },
          { status: 409 },
        );
      }
    }

    // Create member and transaction in a transaction
    const result = await prisma.$transaction(async (tx) => {
      // Create member with standardized amount
      // memberNumber will be auto-generated by the database
      const member = await tx.member.create({
        data: {
          firstName: data.firstName,
          middleName: data.middleName || null,
          surname: data.surname,
          gender: data.gender,
          currentAddress: data.currentAddress,
          city: data.city,
          country: data.country,
          admissionNumber: data.admissionNumber || null,
          dateOfEntry: new Date(data.dateOfEntry),
          dateOfExit: new Date(data.dateOfExit),
          email: data.email || null,
          phone: data.phone,
          registrationAmount: standardizedAmount,
          transactionReference: data.transactionReference,
          systemReference: systemReference,
          status: "pending",
        },
      });

      // Create transaction record
      const transaction = await tx.transaction.create({
        data: {
          memberId: member.id,
          memberName: memberName,
          phone: data.phone,
          amount: standardizedAmount,
          transactionReference: data.transactionReference,
          systemReference: systemReference,
          type: "registration",
        },
      });

      // Send confirmation email (don't await)
      if (member.email) {
        sendRegistrationConfirmation(
          member.email,
          `${member.firstName} ${member.surname}`,
          member.systemReference,
          member.registrationAmount,
          member.transactionReference,
        ).catch((error) => {
          console.error("Failed to send confirmation email:", error);
        });
      }

      return { member, transaction };
    });

    // Return response with memberNumber included
    return NextResponse.json(
      {
        success: true,
        member: {
          id: result.member.id,
          memberNumber: result.member.memberNumber, // Include the sequential number
          firstName: result.member.firstName,
          surname: result.member.surname,
          systemReference: result.member.systemReference,
          status: result.member.status,
        },
        message: "Registration submitted successfully",
      },
      { status: 201 },
    );
  } catch (error) {
    console.error("Registration error:", error);
    return NextResponse.json(
      { error: "Failed to process registration" },
      { status: 500 },
    );
  }
}

// GET endpoint to check registration status
export async function GET(request: Request) {
  try {
    const { searchParams } = new URL(request.url);
    const reference = searchParams.get("reference");

    if (!reference) {
      return NextResponse.json(
        { error: "Reference number required" },
        { status: 400 },
      );
    }

    const member = await prisma.member.findUnique({
      where: { systemReference: reference },
      select: {
        memberNumber: true, // Add this to return the member number
        firstName: true,
        surname: true,
        status: true,
        createdAt: true,
        systemReference: true,
      },
    });

    if (!member) {
      return NextResponse.json(
        { error: "Registration not found" },
        { status: 404 },
      );
    }

    return NextResponse.json({ member });
  } catch (error) {
    console.error("Status check error:", error);
    return NextResponse.json(
      { error: "Failed to check status" },
      { status: 500 },
    );
  }
}
